# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!
service: auth-server

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  timeout: 60 # optional, in seconds, default is 6

functions:
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get

  refreshAccessToken:
    handler: handler.refreshAccessToken
    events:
      - http:
          path: api/refreshtoken/{refresh_code}
          method: get
